FROM python:3.9-slim-bullseye

WORKDIR /app

COPY api.py .
COPY recommendation_model.pickle .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["flask", "--app=api.py", "run", "--host=0.0.0.0", "--port=52047"]
