FROM python:3.9-slim-bullseye

WORKDIR /app

COPY song_recommendation_model_generator.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT python song_recommendation_model_generator.py --dataset-path="$DATASET_PATH"
