apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lucassilva
spec:
  storageClassName: default-storage-class-lucassilva
  selector:
    matchLabels:
      namespace: lucassilva
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi