apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-lucassilva
spec:
  storageClassName: default-storage-class-lucassilva
  volumeName: project2-pv2-lucassilva
  selector:
    matchLabels:
      namespace: lucassilva
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi