apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lucassilva
spec:
  selector:
    matchLabels:
      namespace: lucassilva
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi