# flask-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucassilva-song-recommendation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucassilva-song-recommendation-api
  template:
    metadata:
      labels:
        app: lucassilva-song-recommendation-api
    spec:
      containers:
      - name: lucassilva-song-recommendation-api
        image: lucasgabrios/playlists-recommender-api:1.0.3
        ports:
        - containerPort: 52047
        volumeMounts:
          - mountPath: /app/recommendation
            name: song-recommendation-api-volume
        env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: recomendation-api-config
              key: version
      volumes:
      - name: song-recommendation-api-volume
        persistentVolumeClaim:
          claimName: project2-pvc-lucassilva
