apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucassilva-recommendation-model-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucassilva-recommendation-model-generator
  template:
    metadata:
      labels:
        app: lucassilva-recommendation-model-generator
    spec:
      containers:
      - name: lucassilva-recommendation-model-generator
        image: recommendation-model-generator:1.0.0
        volumeMounts:
          - mountPath: /app/datasets
            name: dataset-volume
      volumes:
      - name: dataset-volume
        persistentVolumeClaim:
          claimName: project2-pvc-lucassilva