apiVersion: batch/v1
kind: Job
metadata:
  generateName: lucassilva-recommendation-model-generator-
spec:
  template:
    metadata:
      labels:
        app: lucassilva-recommendation-model-generator
    spec:
      containers:
      - name: lucassilva-recommendation-model-generator
        image: lucasgabrios/playlists-recommender-model:1.0.2
        volumeMounts:
        - mountPath: /app/datasets
          name: name: dataset-volume
      restartPolicy: Never
      volumes:
      - name: dataset-volume
        persistentVolumeClaim:
          claimName: project2-pvc-lucassilva
  backoffLimit: 3
